# Generated by Django 3.1.7 on 2021-07-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('verbose_name', models.CharField(help_text='Board verbose name.', max_length=20)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name. 14 chars', max_length=14)),
                ('comment', models.TextField(help_text='Comment. 2K chars.', max_length=2000)),
                ('ip', models.GenericIPAddressField()),
                ('image', models.ImageField(upload_to='images/<property object at 0x7fb3e5054770>/')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Thread title.', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x7fb3e4a4de20>/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.board')),
            ],
        ),
    ]
