# Generated by Django 3.1.7 on 2021-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0006_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', help_text='User name. 14 chars', max_length=14),
        ),
    ]
