# Generated by Django 3.1.7 on 2021-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_auto_20210725_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='thread',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
