# Generated by Django 3.2.10 on 2021-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0009_thread_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=None, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='password',
            field=models.CharField(default=None, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
