# Generated by Django 3.2.10 on 2021-12-25 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0010_auto_20211225_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='password',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='name',
            field=models.CharField(default='Anonymous', help_text='User name. 14 chars', max_length=14),
        ),
    ]
