# Generated by Django 3.2.10 on 2021-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0011_auto_20211225_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.GenericIPAddressField(editable=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='ip',
            field=models.GenericIPAddressField(editable=False),
        ),
    ]
