# Generated by Django 3.2.10 on 2021-12-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0012_auto_20211226_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='static/no_image.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default='static/no_image.jpeg', upload_to=''),
        ),
    ]
