# Generated by Django 3.2.10 on 2021-12-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0013_auto_20211226_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
