# Generated by Django 3.1.7 on 2021-07-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='images/<property object at 0x7f6e9a64c810>/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x7f6e9a045e20>/'),
        ),
    ]
