# Generated by Django 3.1.7 on 2021-07-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_auto_20210717_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='imageboard.thread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='text',
            field=models.TextField(default='', help_text='OP text. Max 4K chars.', max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
