# Generated by Django 3.1.7 on 2021-08-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0008_auto_20210805_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.42.6'),
            preserve_default=False,
        ),
    ]
